site_name: Stories
site_url: https://pamlib.github.io/stories/
repo_name: pamlib/stories
repo_url: https://github.com/pamlib/stories

theme:
  name: material
  language: en
  custom_dir: docs/assets/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Stories:
    - "Toon's Quest to Save the Infinite Yield Script": stories/toonsquesttosavetheinfiniteyieldscript.md
    - "Scott's Treasure Hunt": stories/scottstreasurehunt.md
    - "Games and The Age": stories/gamesandtheage.md
    - "Infinite Yield: The Team Behind the Script": stories/infiniteyieldtheteambehindthescript.md
    - "Matt in the Backrooms": stories/mattinthebackrooms.md
    - "The Curse of the Abandoned Mansion": stories/thecurseoftheabandonedmansion.md
    - "The Possessed Mansion: A Tale of Haunted Souls and Forbidden Knowledge": stories/thepossessedmansion.md
    - "Bomb Island": stories/bombisland.md
    - "The Infinite Library": stories/theinfinitelibrary.md
    - "The Space-Time Crystal": stories/thespacetimecrystal.md


markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
